Repository ispp-2324-ocial/backend, pull requests merged in 2024-03, with the labels that each got.

#17 ci: baseline implementation
  .github/workflows/quality_checks.yml
Labels: code, enhancement, blocked

#68 fix: event methods
  event/views.py
  user/views.py
Labels: backend, hotfix

#74 fix(event): codigo inutilizado en el models de event
  event/models.py
Labels: backend, code, hotfix
